[package]
name = "common"
version = "0.8.0"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2018"

[dependencies]
lz4-compress = { path = "../lz4-compress" }
speedy = "0.8"
byteorder = "1"
libc = "0.2"
