[package]
name = "memory-profiler-gather"
version = "0.6.1"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2018"

[dependencies]
clap = { version = "2", default-features = false }
log = "0.4"
chrono = "0.4"
cli-core = { path = "../cli-core" }
