[package]
name = "memory-profiler"
version = "0.2.0"
authors = ["Jan Bujak <jan.bujak@nokia.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
parking_lot = { version = "0.7", features = ["nightly"] }
lock_api = "0.1"
libc = "0.2"
sc = "0.2"
lazy_static = "1"
fnv = "1"
smallvec = "0.6"
memmap = "0.7"
log = "0.4"
glob = "0.2"
jemallocator = { path = "../jemallocator", default-features = false }
jemalloc-sys = { path = "../jemallocator/jemalloc-sys", default-features = false }

[dependencies.nwind]
git = "https://github.com/nokia/not-perf.git"
rev = "261a999"
features = ["log", "local-unwinding"]
default-features = false

[dependencies.perf_event_open]
git = "https://github.com/nokia/not-perf.git"
rev = "261a999"

[dependencies.common]
path = "../common"

[features]
default = []
debug-logs = ["nwind/debug-logs", "nwind/addr2line"]
